### ISSUE TITLE
No Documentation for generating basic auth password

### ISSUE THREAD

**Issue by bryaend** [techno-tim/techno-tim.github.io#101]
https://github.com/techno-tim/techno-tim.github.io/blob/a351a2173bdd5c9ade3e92e9f2b22f3a3da94e41/reference_files/traefik-portainer-ssl/traefik/docker-compose.yml#L30

For new users, this step may be difficult and confusing as to why they are not able to set their password properly and log in to the Traefik dashboard. There should exist documentation for how to configure this.

**Comment by thebassy** [comment]
@bryaend See the write up here: https://techno-tim.github.io/posts/traefik-portainer-ssl/#generate-basic-auth-password

**Comment by timothystewart6** [comment]
This is already documented in the post and code :)  Thank you! https://techno-tim.github.io/posts/traefik-portainer-ssl/
