### ISSUE TITLE
Add documentation on which permissions does the API Token need

### ISSUE THREAD

**Issue by jruiz94** [techno-tim/techno-tim.github.io#248]
Hello I was reading through the code following the tutorial on adding Traefik and SSL on everything and I reached the part where I have to fill in Cloudflare's API Token.

However when creating API Tokens Cloudflare asks you which permissions do you want for the API token.

I don't know which permissions to set, and it seems a little bit of a security issue to allow everything so what are the permissions needed for this to work? Could a comment be added [here](https://github.com/techno-tim/techno-tim.github.io/blob/39008c32fc372cb77142566bc4a321fed40f8deb/reference_files/traefik-portainer-ssl/traefik/docker-compose.yml#L19) with the permissions to add?

Thanks in advance

**Comment by rainyskye** [comment]
I remember having the same question at some point, it does mention in the traefik documentation what permissions are required. I'll see if I can find them.

**Comment by rainyskye** [comment]
@jruiz94 https://go-acme.github.io/lego/dns/cloudflare/#api-tokens

The docs state
- Zone / Zone / Read
- Zone / DNS / Edit

It also states how you can create separate keys, one to be able to read all of your zones, and another one to edit with only the domain(s) you want within scope.

**Comment by jruiz94** [comment]
Thanks a ton!!
