### ISSUE TITLE
Misleading password label

### ISSUE THREAD

**Issue by jackchenry** [techno-tim/techno-tim.github.io#310]
Tiny thing but line12 in reference_files/traefik-portainer-ssl/traefik/users_database.yml says "# Password is Authelia" when in fact the hashed password is "P@assword!".

**Comment by timothystewart6** [comment]
Thanks!  If you want to open a pull request that would be great!  Otherwise I will fix it soon!

**Comment by timothystewart6** [comment]
Hey!  Going to close this issue.  It's better to post this on the blog post you are having issues
