### ISSUE TITLE
Change in syntax for proxmox template blog post

### ISSUE THREAD

**Issue by 0lzi** [techno-tim/techno-tim.github.io#321]
https://techno-tim.github.io/posts/cloud-init-cloud-image/

```
Import the downloaded Ubuntu disk to local-lvm storage
 
--

qm importdisk 8000 jammy-server-cloudimg-amd64.img local-lvm

```

Didn't work on PVE 8.2.2 .

The correct syntax seems to be `qm disk import <vmid> <server.img> local-lvm`

**Comment by timothystewart6** [comment]
Thank you!  If you'd like to open a PR, the post is here, otherwise I will when I can!
https://github.com/techno-tim/techno-tim.github.io/blob/master/_posts/2022-03-19-cloud-init-cloud-image.md
