### ISSUE TITLE
I'm struggle-bussing with idrac

### ISSUE THREAD

**Issue by DeathTater** [techno-tim/techno-tim.github.io#323]
I'm using the config.yml in reference files > traefik-portainer-ssl >traefik > config.yml.  

The config file is working like a champ all of my services such as pihole, proxmox, unraids, plex, portainer, etc are working perfectly.  Idrac on the other hand is giving me nothing but Access Error: 400 -- Bad Request.  Getting to the idrac via IP address works perfectly fine.

This is what the idrac section of the config looks like.

http:
 #region routers
  routers:
	  idrac:
      entryPoints:
        - "https"
      rule: "Host(`idrac.domain.com`)"
      middlewares:
        - idrac
        - https-redirectscheme
      tls: {}
      service: idrac
    idrac-console:
      entryPoints:
        - "idrac" # REQUIRED for iDRAC virtual console: Create a new TCP entry point in traefik on port 5900
      rule: "Host(`idrac.domain.com`)"
      middlewares:
        - idrac
        - https-redirectscheme
      tls: {}
      service: idrac-console

#endregion
#region services
  services:
	idrac:
      loadBalancer:
        servers:
          - url: "https://172.16.0.139"
        passHostHeader: true
    idrac-console:
      loadBalancer:
        servers:
          - url: "https://172.16.0.139:5900"
        passHostHeader: true

#endregion
  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    redirectregex-pihole:
      redirectRegex:
        regex: "/admin/(.*)"
        replacement: /

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    idrac:
      headers:
        frameDeny: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

On the Traefik Dashboard I was getting errors about the entry point not being found so I added idrac to the traefik.yml file.

api:
  dashboard: true
  debug: true
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
  idrac:
    address: ":5900"

My cname entry for idrac is pointing to the same target domain on Pi-hole like all of my other entries.  

What do I have configured wrong?  I would like to have this fixed soon as I have two more poweredge servers on the way.

**Comment by timothystewart6** [comment]
Hey!  Going to close this issue.  It's better to post this on the blog post you are having issues
