### ISSUE TITLE
Update to first-13-things-linux

### ISSUE THREAD

**Issue by bryanmahler** [techno-tim/techno-tim.github.io#34]
The line:
/etc/apt/apt.conf.d/50-unattended-upgrades

should be:
/etc/apt/apt.conf.d/50unattended-upgrades

Thanks!

**Comment by bryanmahler** [comment]
"sudo ufw default allow outgoing" can also be added under the firewall section

**Comment by timothystewart6** [comment]
If you'd like to open a PR, all files are located here: https://github.com/techno-tim/techno-tim.github.io/tree/master/_posts

**Comment by timothystewart6** [comment]
this was fixed!  thank you!
