### ISSUE TITLE
Update to docker-rancher-kubernetes

### ISSUE THREAD

**Issue by bryanmahler** [techno-tim/techno-tim.github.io#35]
A potentially better link for finding the latest Rancher version may be: https://github.com/rancher/rancher/tags

The Rancher team has begun using a lot of tags on the original page: https://hub.docker.com/r/rancher/rancher/tags?page=1&ordering=last_updated

**Comment by timothystewart6** [comment]
If you'd like to open a PR, all files are located here: https://github.com/techno-tim/techno-tim.github.io/tree/master/_posts

**Comment by timothystewart6** [comment]
fixed in https://github.com/techno-tim/techno-tim.github.io/commit/cd4b9de29478db343ae394329556128f7bd4f05a  thank you!
