### ISSUE TITLE
Update to rancher-2-upgrade-backup-restore

### ISSUE THREAD

**Issue by bryanmahler** [techno-tim/techno-tim.github.io#36]
Two commands are missing the <DATE> template text:

Change:
docker create --volumes-from <RANCHER_CONTAINER_NAME> --name rancher-data rancher/rancher:<RANCHER_CONTAINER_TAG>
to:
docker create --volumes-from <RANCHER_CONTAINER_NAME> --name rancher-data-<DATE> rancher/rancher:<RANCHER_CONTAINER_TAG>

And change:
docker run --volumes-from rancher-data -v $PWD:/backup busybox tar zcvf /backup/rancher-data-backup-<RANCHER_VERSION>-<DATE>.tar.gz /var/lib/rancher
to:
docker run --volumes-from rancher-data-<DATE> -v $PWD:/backup busybox tar zcvf /backup/rancher-data-backup-<RANCHER_VERSION>-<DATE>.tar.gz /var/lib/rancher

Thanks again!

**Comment by bryanmahler** [comment]
Looking at this again today... this may be a Github issue the DATE text in brackets is visible in the text editor but not in the display text visible to users. Github may use that text combination itself.

**Comment by timothystewart6** [comment]
If you'd like to open a PR, all files are located here: https://github.com/techno-tim/techno-tim.github.io/tree/master/_posts

**Comment by timothystewart6** [comment]
fixed in https://github.com/techno-tim/techno-tim.github.io/commit/3cf882d71082d39a949c082178c4c84b070bd08b thank you!
