### ISSUE TITLE
There is an official way for regenerating a machine-id

### ISSUE THREAD

**Issue by j0holo** [techno-tim/techno-tim.github.io#42]
I was bumping into the same issue when cloning VMs in Proxmox VE. After a lot of searching I found a way to generate a new machine-id without rebooting the VM.

[https://wiki.debian.org/MachineId](https://wiki.debian.org/MachineId)

```
rm -f /etc/machine-id /var/lib/dbus/machine-id
dbus-uuidgen --ensure=/etc/machine-id
dbus-uuidgen --ensure
```
This generates a new machine id at `/etch/machine-id` and `/var/lib/dbus/machine-id` without rebooting.
https://github.com/techno-tim/youtube-videos/tree/master/first-11-things-proxmox could be updated to use the "correct" way of resetting a machine-id?

**Comment by timothystewart6** [comment]
If you'd like to open a PR, all files are located here: https://github.com/techno-tim/techno-tim.github.io/tree/master/_posts

**Comment by timothystewart6** [comment]
fixed in https://github.com/techno-tim/techno-tim.github.io/commit/87e31179528e5debd7c7de9c9af5968878a06939 thank you!

**Comment by j0holo** [comment]
Sorry for not opening a PR.
