### ISSUE TITLE
The description of episode is wrong

### ISSUE THREAD

**Issue by Hermanverschooten** [techno-tim/techno-tim.github.io#47]
The post 2021-02-01-deep-learning-my-life has the same description underneath the video as the ventoy episode.

**Comment by timothystewart6** [comment]
thank you!

**Comment by timothystewart6** [comment]
This was fixed in https://github.com/techno-tim/techno-tim.github.io/commit/2f7d512209dfdaf945442f8319847f60e8039f5f  Thank you!
