### ISSUE TITLE
K3s Install addition

### ISSUE THREAD

**Issue by darkcloud784** [techno-tim/techno-tim.github.io#50]
As mentioned in discord I would recommend adding the following to your k3s deployment. I see multiple pages about the k3s deployment and each are missing the following which will make sure the nodes stay alive even if you over provision pods.

`INSTALL_K3S_EXEC= ........  --kubelet-arg system-reserved=cpu=100m,memory=100Mi --kubelet-arg kube-reserved=cpu=200m,memory=400Mi`

**Comment by timothystewart6** [comment]
Thank you!

**Comment by timothystewart6** [comment]
Hey!  Going to close this issue.  It's better to post this on the blog post you are having issues
