### ISSUE TITLE
Traefik - Missing command

### ISSUE THREAD

**Issue by upstreamsea** [techno-tim/techno-tim.github.io#51]
Currently, the "Traefik" portion of the command list has the following commands, in order:

**mkdir traefik
cd traefik
mkdir data
touch acme.json
chmod 600 acme.json
touch traefik.yml**

In the video, you show yourself going into ./traefik/data to perform the following commands:

**touch acme.json
chmod 600 acme.json
touch traefik.yml**

Current command structure should be:

**mkdir traefik
cd traefik
mkdir data
cd data
touch acme.json
chmod 600 acme.json
touch traefik.yml**

**Comment by timothystewart6** [comment]
thank you!

**Comment by timothystewart6** [comment]
fixed in https://github.com/techno-tim/techno-tim.github.io/commit/8acf5be693e8c28d48179a6bb63b76f6e5fbadbd  Thank you!
