### ISSUE TITLE
can't generate cert. "help wanted"

### ISSUE THREAD

**Issue by drmaq** [techno-tim/techno-tim.github.io#55]
I have gotten setup to this point however I run into this error:

>  time="2021-04-27T22:51:14Z" level=info msg="Configuration loaded from file: /traefik.yml"
> time="2021-04-27T22:51:21Z" level=error msg="Unable to obtain ACME certificate for domains \"local.xyznetwork.page,*.local.xyznetwork.page\" : unable to generate a certificate for the domains [local.xyznetwork.page *.local.xyznetwork.page]: error: one or more domains had a problem:\n[*.local.xyznetwork.page] [*.local.xyznetwork.page] acme: error presenting token: cloudflare: failed to find zone xyznetwork.page.: ListZonesContext command failed: HTTP status 400: Invalid request headers (6003)\n[local.xyznetwork.page] [local.xyznetwork.page] acme: error presenting token: cloudflare: failed to find zone xyznetwork.page.: ListZonesContext command failed: HTTP status 400: Invalid request headers (6003)\n" providerName=cloudflare.acme
> 

My dns provider is cloudflare I have add the api key from cloudflare. The config has not changed other than the placeholder values.
What am I doing wrong. please let me know what other info that I can provide to receive help

**Comment by timothystewart6** [comment]
Hi! This doesn't look like an issue with the repo but a general question. Feel free to join our Discord community and ask there! https://discord.gg/DJKexrJ

**Comment by drmaq** [comment]
thanks for letting me know
