### ISSUE TITLE
FQDN vs host name.

### ISSUE THREAD

**Issue by kg6ebj** [techno-tim/techno-tim.github.io#61]
Hello Tim!! I am very glad to have stumbled across some of the work you have been doing, however I have gotten stuck with an issue I hope you can help me resolve.
If I enter the FQDN I get the cert for *.example.tld
If I enter the Host (within my search domain) I get a cert for traefik.

am I just dense, or did I miss a step?

thanks, and any additional help would I will be grateful for.

**Comment by timothystewart6** [comment]
Hi! This doesn't look like an issue with the repo but a general question. Feel free to join our Discord community and ask there! https://discord.gg/DJKexrJ
