### ISSUE TITLE
Advertise RSS Feed

### ISSUE THREAD

**Issue by reesericci** [techno-tim/techno-tim.github.io#63]
You should put somewhere on your website (maybe on the sidebar next to the socials) that the RSS feed is at /feed.xml. A lot of techies use RSS daily and advertising it would be a plus.

-reese

**Comment by timothystewart6** [comment]
Thank you @reesericci !  I will consider it!

**Comment by timothystewart6** [comment]
Fixed in https://github.com/techno-tim/techno-tim.github.io/commit/ef141c2ef9ac0f84ffd0aae5771a9a5080386a6e

Feed is at https://techno-tim.github.io/feed.xml and icon on sidebar!
