### ISSUE TITLE
Small Issue in 2 Factor Auth and Single Sign on with Authelia

### ISSUE THREAD

**Issue by CaptMcAwesome** [techno-tim/techno-tim.github.io#65]
Morning,

Thanks for the new video.   Amazing stuff.   There is one super small issue on the document server with this page -->  https://techno-tim.github.io/posts/authelia-traefik/

You are missing an "s" in the file name of users_database.yml
![user](https://user-images.githubusercontent.com/66213369/120926417-98243780-c691-11eb-91a2-9716d2fefd79.PNG)

Thanks for all your hard work!  Look forward to the next video.

McAwesome

**Comment by timothystewart6** [comment]
Thank you!  Will fix!

**Comment by timothystewart6** [comment]
Fixed by https://github.com/techno-tim/techno-tim.github.io/commit/67ec68ce2fd75189e464a35cc249e52b2c3f2789  Thank you!
