### ISSUE TITLE
Transmission route does not work via config.yml (external service) or Internal (Traefik's network)

### ISSUE THREAD

**Issue by rexdavid** [techno-tim/techno-tim.github.io#67]
In Config:
...
    transmission:
      entryPoints:
        - "https"
      rule: "Host(`transmission.rexrd.com`)"
      middlewares:
        - default-headers
        - addprefix-transmission
      tls: {}
      service: transmission
....

#endregion
  middlewares:
    addprefix-transmission:
      addPrefix:
        prefix: "/transmission/web/"
    https-redirect:
      redirectScheme:
        scheme: https
    authelia: # This is NEW
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://auth.example.com"  
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
....

**Comment by timothystewart6** [comment]
Hey!  it looks like this a question or a problem with traefik and not a problem with the code here.  Please join our Discord for questions!  https://discord.gg/DJKexrJ
