### ISSUE TITLE
Traefik Config Https Redirection

### ISSUE THREAD

**Issue by rexdavid** [techno-tim/techno-tim.github.io#73]
Issue: Https Redirection doesn't work as per the config.yml:

http: 
  routers: 
    proxmox: 
      entryPoints: 
        - "https" 
      rule: "Host(`proxmox.example.com`)" 
      middlewares: 
        - authelia 
        - default-headers 
      tls: {} 
      service: proxmox 
    truenas: 
      entryPoints: 
        - "https" 
      rule: "Host(`truenas.example.com`)" 
      middlewares: 
        - authelia 
        - default-headers 
      tls: {} 
      service: truenas 
    nextcloud: 
      entryPoints: 
        - "https" 
      rule: "Host(`nextcloud.example.com`)" 
      middlewares: 
        - default-headers 
      tls: {} 
      service: nextcloud 
#endregion 
#region services 
  services: 
    proxmox: 
      loadBalancer: 
        servers: 
          - url: "https://192.168.177.11:8006" 
        passHostHeader: true 
    truenas: 
      loadBalancer: 
        servers: 
          - url: "https://192.168.177.5" 
        passHostHeader: true 
    nextcloud: 
      loadBalancer: 
        servers: 
          - url: "https://192.168.177.9:4430" 
        passHostHeader: true    
    
#endregion 
  middlewares: 
    https-redirect: 
      redirectScheme: 
        scheme: https 
    authelia: # This is NEW 
      forwardAuth: 
        address: "http://authelia:9091/api/verify?rd=https://auth.example.com"   
    default-headers: 
      headers: 
        frameDeny: true 
        sslRedirect: true 
        browserXssFilter: true 
        contentTypeNosniff: true 
        forceSTSHeader: true 
        stsIncludeSubdomains: true 
        stsPreload: true 
        stsSeconds: 15552000 
        customFrameOptionsValue: SAMEORIGIN 
        customRequestHeaders: 
          X-Forwarded-Proto: https 
    secured: 
      chain: 
        middlewares: 
        #- default-whitelist 

Thanks for the video walkthrough.

**Comment by timothystewart6** [comment]
Hey! This looks like this a question or a problem with traefik and not a problem with the code here. Please join our Discord for questions! https://discord.gg/DJKexrJ
