### ISSUE TITLE
Unable to obtain ACME certificate for domains \"local...

### ISSUE THREAD

**Issue by rage4design** [techno-tim/techno-tim.github.io#80]
Excellent write up.  Loved the youtube instructions.  Everything worked like a charm.

I only ran into a small issue: The certificates filed to create with error:

```log
traefik    | time="2021-09-19T15:34:45-05:00" level=error msg="Unable to obtain ACME certificate for domains \"local.example.tld,*.local.example.tld\" : unable to generate a certificate for the domains [local.example.tld *.local.example.tld]: error: one or more domains had a problem:\n[*.local.example.tld] time limit exceeded: last error: NS ....ns.cloudflare.com. did not return the expected TXT record [fqdn: _acme-challenge.local.example.tld., value: .....]: \n[local.example.tld] time limit exceeded: last error: NS ....ns.cloudflare.com. did not return the expected TXT record [fqdn: _acme-challenge.local.example.tld., value: ...]: \n" providerName=cloudflare.acme
^CERROR: Aborting.
``` 

The fix was to place the wildcard to `main` and the without wildcard to `sans`

```yaml
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=*.local.example.tld"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=local.example.tld"
```

After this, both certificates got generated and saved in acme.json

**Comment by rage4design** [comment]
Sorry about that.  I think the problem arose during testing and possibly too frequent certificate renewals.

In the end, I did remove the wildcard domain and replaced it with `traefik-dashboard.local.example.tld`

Also added the same labels for each of the individual service to create certificates for each URL.  

But this is just a minor change. 

The documentation and the git was so helpful.

**Comment by timothystewart6** [comment]
Sounds good!  Glad you sorted it out!
