### ISSUE TITLE
Traefik acme client invalid config

### ISSUE THREAD

**Issue by TheProf200** [techno-tim/techno-tim.github.io#82]
I was following the new Traefik 2, k3s, Rancher guide and i found a acme client issue with the traefik-chart-values.yml. The CF_DNS_API_TOKEN Needed a change to CF_API_KEY

**Comment by timothystewart6** [comment]
Hi!  Thank you!  I think you can use either ENV but you have to supply the correct variable

**Comment by crawler-n** [comment]
I was having the same issue. Created a PR for you. #83

**Comment by timothystewart6** [comment]
closed by https://github.com/techno-tim/techno-tim.github.io/pull/83  Thank you!

**Comment by timothystewart6** [comment]
@damjankumin   feel free to join our discord for help!
