### ISSUE TITLE
Authelia

### ISSUE THREAD

**Issue by AlmostChopper** [techno-tim/techno-tim.github.io#99]
In the authelia configuration.yml you need to update this:

host: 0.0.0.0
port: 9091
log_level: debug

to this:

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

**Comment by timothystewart6** [comment]
fixed by https://github.com/techno-tim/techno-tim.github.io/commit/a351a2173bdd5c9ade3e92e9f2b22f3a3da94e41  Thank you!
